### PR TITLE
 update user details

### PR DESCRIPTION
**Pull request by mark-nakachon**
### **Problem**
the problem is about updating the entire bio of user details.
### **Solution of the problem **
i added 2 controller functions which gets the details of users when the DOM content loads and a user can update the details and these details are successfully saved inside this mongodb database
i even added a acknowledgment message which lasts for 2 seconds that the details have been updated

### **Type of Change**
-[ ] New Feature

### **Checklist **
- [x] My code follow the same style as the codebase
- [x] i made PR within **development branch only **
- [x] i made this pull request by resolving the issue #81

### CODE REVIEW

**Comment by prateekiiest** [comment]
Please resolve the above conflicts first.

**Comment by mark-nakachon** [comment]
I resolved the conflicts please review this

**Comment by prateekiiest** [comment]
Could you make a screenshot of the final changes on the site?

**Comment by jaskirat2000** [comment]
This PR will not be merged unless it follows PR template, please follow PR template and make it again else tgis would be closed.
Thanka

**Comment by jaskirat2000** [comment]
You have not check listed any of the above

**Comment by mark-nakachon** [comment]
i check listed please review this once

**Comment by jaskirat2000** [comment]
Thanks

**Pull request merged**
