### PR TITLE
Memory leakage tracking issue solved

### LINKED ISSUE #126: Adding Memory leakage tracking
### **Description of the problem**
For now memory leakage of any kind is not tracked . There are some kind of leakages like you can see in this article.https://medium.com/tech-tajawal/memory-leaks-in-nodejs-quick-overview-988c23b24dba

### **How to solve**
Add some tracker to track the stats and leakage so that leakage can be removed.

### **Expected Outcome**
Getting a log of stats related to memory leakage

### PR DESCRIPTION
**Pull request by TG1999**
### **Problem**
There was no tracking for memory leakage before

### **Issue this PR referred to**
`Fixes #126`

### **Solution of problem**
Adding node memwatch for tracking memory leakage

### **Before and After Screenshots**
_**Before** [How was it earlier, add it here]_

_**After** [How it looks now, add it here]_
screenshot 2019-03-04 at 5 24 59 pm

### **Type of Change**
- [ ] Bug fix
- [x] New Feature
- [ ] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follow the same style as the codebase
- [x] My Code changed required change in documentation
- [x] I have updated the Readme accordingly
- [x] I made PR within **development branch only**

### CODE REVIEW

**Comment by TG1999** [comment]
@jaskirat2000 What's the status of my PR review?

**Comment by iamgrawal** [comment]
@TG1999 which issue is this pull request referred to ?

**Comment by TG1999** [comment]
#126 

> @TG1999 which issue is this pull request referred to ?

**Comment by vaibhavdaren** [comment]
good work

**Pull request merged**
