### PR TITLE
Facebook Login Setup

### PR DESCRIPTION
**Pull request by moulikcipherX**
Resolve Issue #33

### CODE REVIEW

**Comment by jaskirat2000** [comment]
Hey its good work.
Let other see it once. @sdsahib @iamgrawal

**Comment by capedcrusader23** [comment]
You need to refer from github oauth not to delete that

**Comment by moulikcipherX** [comment]
@sdsahib can you merge this PR for once Please..

**Comment by sdsahib** [comment]
> @sdsahib can you merge this PR for once Please..

hey can you make sure that all the logins buttons are working properly and user is able to login. Check the all.ejs. Because login with google and github are not working after your changes.

**Comment by moulikcipherX** [comment]
Okay I will look

**Comment by moulikcipherX** [comment]
Yeah I have looked it is because of UI.

**Comment by sdsahib** [comment]
just make it work I will ask someone to fix the UI

**Comment by moulikcipherX** [comment]
All the links are working when UI is fixed

**Pull request merged**
