### PR TITLE
Routes to send JSON data instead of rentering views

### PR DESCRIPTION
**Pull request by lakshyabatman**
Changed Most of the render commands to send, so now Routes will send JSON instead of rendering Pages.

Issues still left to handle:

Login Route isn't working.

The whole project is on passport so, on building the frontend on vue, we need to add JWT, so we require to build up new SIGNUP and LOGIN routes.

the auth middleware in the profile.routes.js is just a simple check function, it checks whether req.user is present or not. We need to build better authentication using JWT.

@capedcrusader23 , @jaskirat2000 , @vaibhavdaren , @devshiva619

note: I tried to squash commits, but it failed, that's why I have 5 commits.

### CODE REVIEW

**Comment by jaskirat2000** [comment]
Thanks @lakshyabatman

**Comment by vaibhavdaren** [comment]
Nice Work :100:

**Comment by vaibhavdaren** [comment]
i help you with squash

**Comment by lakshyabatman** [comment]
@vaibhavdaren Yes sure :)

**Pull request merged**
