### PR TITLE
Schema Changes

### PR DESCRIPTION
**Pull request by kiransaha**
### **Problem**
_Schema for DB_

### **Solution of problem**
_I have made changes to the schema in two files namely project.js and user.js in reference to the issue #146 _

### **Type of Change**
- [x] Bug fix

### **Checklist**
- [ ] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [ ] I have updated the Readme accordingly
- [x] I made PR within **development branch only**

### CODE REVIEW

**Comment by nurdtechie98** [comment]
@kiransaha thanks for the pull request, please make sure you follow the pr template provided [here](https://github.com/codeuino/Social-Platform-Donut/blob/master/.github/ISSUE_TEMPLATE/pull-request-template.md) and fix the merge conflict.

**Comment by kiransaha** [comment]
@nurdtechie98  Ok will keep that in check thanks

**Comment by kiransaha** [comment]
done @nurdtechie98

**Comment by nurdtechie98** [comment]
@kiransaha always provide reference to the issue addressed In this case #146 , other than remove the merge conflicts

**Comment by kiransaha** [comment]
> @kiransaha always provide reference to the issue addressed In this case #146 , other than remove the merge conflicts

reference mentioned, do suggest further changes if any

**Comment by nurdtechie98** [comment]
@kiransaha , please remove the merge conflict.

**Comment by prateekiiest** [comment]
Any update on this @kiransaha ?

**Comment by prateekiiest** [comment]
Should we close this then ?

**Comment by iamgrawal** [comment]
Hey, @kiransaha since It has been a long time since that there are not any updates on the PR, so I am closing it. Feel free to create another PR once you are done with the changes.

**Pull request closed without merging**
