### PR TITLE
complete routing signup + login

### LINKED ISSUE #125: signup problem
### **Description of the problem**
this problem is about signing up a user although there is a sign up page it is not styled and the post request to /userlogin route is not working and when a user signs up his/her details are not stored in the database 

### **How to solve**
i will solve this issue by adding a /signup route and handle the logic of signing up the user and saving the details in the database and logging in the user after signing up

### **Expected Outcome**
after resolving this issue a user can sign up and his/het details will be succesfully saved in the database

i am assigning this issue to myself

### PR DESCRIPTION
**Pull request by nurdtechie98**
### **Problem**
The signup and login for individual was present in front end not here, thus currently login/signup with email was dead. There was some error in password matching as well
### **Solution of problem**
- [X] add and modify signup template from frontend repo
- [X] add land modify login template from frontend repo
- [X] add signup route
- [X] add login route
- [X] fix bugs in user scheme

### **Before and After Screenshots**
**Before** 
[None]

**After** 
[demo gif link](https://i.imgur.com/J0Qv82I.gif)

### **Type of Change**
- [X] Bug fix
- [X] New Feature
- [ ] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [X] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [ ] I have updated the Readme accordingly
- [X] I made PR within **development branch only**

Closes #125

### CODE REVIEW

**Comment by nurdtechie98** [comment]
@capedcrusader23 @jaskirat2000 please review and let me know for some changes :smile:

**Comment by lakshyabatman** [comment]
@capedcrusader23 , please review the code.

**Comment by mark-nakachon** [comment]
@nurdtechie98 didn't u see that there is a passport local strategy in /config/local.js u should use that local strategy for both loggin in and also for signup purpose
since u did not adopt passport and done manually (which i was thinking to do) remove the /config/local.js
and if this pull request is  merged this will solve #125 #117 an these 2 issues can be closed

**Comment by capedcrusader23** [comment]
yes i agree with @mark-nakachon ,please use passport.local to authenticate users

**Comment by nurdtechie98** [comment]
Ou I missed out on that. I'll add it then👍🏻

**Comment by iamgrawal** [comment]
@nurdtechie98 @capedcrusader23  any update on this PR, since it has been a long time this PR has been created.

**Comment by iamgrawal** [comment]
Hey @nurdtechie98, Since it has been so long that no updates have been given. So I am closing this PR. Feel free to create another PR once done.

**Pull request closed without merging**
