### PR TITLE
Passwords in SignUp Not Matching fixed

### PR DESCRIPTION
**Pull request by pragun22**
### **Problem**
Organisations signup page password and retype password validator not functioning properly. Showing error even when passwords match
### **Issue this PR referred to**
Fixes issue number 182, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/182) for more details_

### **Solution of problem**
in the file /views/js/signup_validator.js for finding the value of pass and cpass, after writing .getElementByID() also add .innerhtml for getting the entered values.

### **Before and After Screenshots**
Alt text

### **Type of Change**
- Small refactor

### **Checklist**
- My code follow the same style as the codebase
- My Code changed required change in documentation
- I have updated the Readme accordingly
- I made PR within **development branch only**

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
why 2 commits? 1 feature 1 commit

**Comment by prateekiiest** [comment]
I am not sure if this will conflict with #204

**Comment by lakshyabatman** [comment]
I tested the signup module so it won't be a issue in frontend side . :)

**Comment by prateekiiest** [comment]
I guess this can be merged in

**Pull request closed without merging**
