### PR TITLE
improved search button styling

### LINKED ISSUE #80: Remove Search button and add font-awesome magnifying glass icon in search bar
ss2

ss3

Try to change the navbar of donut from former to latter

### PR DESCRIPTION
**Pull request by thobhanifreddy**
### **Problem**
_Describe the problem you are trying to achieve. Please provide in detail_

### **Issue this PR referred to**
 `Fixes #80 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/80) for more details_

### **Solution of problem**
Used bootstrap 4 form  control and little bit of css. Stylesheet was not linked correctly so fixed stylesheet path,  

### **Before and After Screenshots**
Screenshot 2019-03-09 at 10 59 50

screenshot 2019-03-06 at 21 45 44

### **Type of Change**
- [ ] Bug fix
- [ ] New Feature
- [x] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [ ] I have updated the Readme accordingly
- [x] I made PR within **development branch only**

### CODE REVIEW

**Comment by iamgrawal** [comment]
Hey @thobhanifreddy, this pull request is not in the required format of the pull request template. I would request you to kindly edit it to the required format. 
You can refer to the template [here](https://raw.githubusercontent.com/codeuino/Social-Platform-Donut/master/PR_Template.md)

**Comment by thobhanifreddy** [comment]
@iamgrawal  updated :)

**Comment by nurdtechie98** [comment]
@thobhanifreddy you have a merge conflict because of recent changes. Do pull the changes and push back to your development branch that should make it able to merge.

**Comment by nurdtechie98** [comment]
also looking at the issue you have referenced it seems there is a confusion regarding whether this issue is still up or not. @jaskirat2000 please clear the confusion whether #80 is still open.

**Comment by devshiva619** [comment]
@thobhanifreddy please solve the merge conflict.

**Comment by thobhanifreddy** [comment]
@devshiva619  no conflict now... :)

**Pull request merged**
