### PR TITLE
Issue165: auth/login route not working  

### PR DESCRIPTION
**Pull request by pragun22**
### **Problem**
data.compare was not working in login.routes.js 
### **Issue this PR referred to**
Fixes issue number #165 , Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/165) for more details_

### **Solution of problem**
Compare was not working as data received is in the form of struct and .compare does not work for them.  So I replaced it with a  "=="  operator to compare passwords of both structs. 

### **Before and After Screenshots**
# error/problem
Screenshot from 2019-04-17 01-53-38

# output of request after solving the problem
Screenshot from 2019-04-17 01-59-51

Screenshot from 2019-04-17 01-59-46

### **Type of Change**
- Small refactor

### **Checklist**
- My code follow the same style as the codebase
- My Code changed required change in documentation
- I have updated the Readme accordingly
- I made PR within **development branch only**

### CODE REVIEW

**Comment by TG1999** [comment]
Okay I will test the route with your code once @pragun22 if it's good their I will tell here. 😄 .If you have tested the route already then please tell .

**Comment by pragun22** [comment]
@TG1999  I have done some basic testing like just sending a request with headers through postman(screenshot is attached in the PR) and npm request, you can do deep testing of the route.

**Comment by prateekiiest** [comment]
@pragun22 , before anything else, please rename your PR and follow the best practices of PR naming.

**Comment by pragun22** [comment]
@prateekiiest  thanks for the feedback, I have changed PR name. kindly check if it is alright.

**Comment by TG1999** [comment]
https://github.com/codeuino/Social-Platform-Donut/pull/185#issuecomment-483992395
I can do testing only after the commit gets merged @pragun22 so let's mentor have a look on it. Then I will test this route.😃

**Comment by TG1999** [comment]
@pragun22  please make different branch for solving different issues.

**Comment by vaibhavdaren** [comment]
why 3 commits ?

**Comment by pragun22** [comment]
@vaibhavdaren  I may have mixed some branches(sorry for that),
Yeah, @TG1999  I will be making new PR with a different branch.
For now, I am closing this PR

**Pull request closed without merging**
