### PR TITLE
Improved Sign Up Look 

### PR DESCRIPTION
**Pull request by shakti97**
screenshot 25 Before
screenshot 26 After

### CODE REVIEW

**Comment by prateekiiest** [comment]
@shakti97 have you opened a corresponding issue for this?

**Comment by shakti97** [comment]
Issue #101

**Comment by jaskirat2000** [comment]
Can you change the white background to something ?

**Comment by shakti97** [comment]
screenshot 30
After changing the default background @jaskirat2000

**Comment by jaskirat2000** [comment]
Looks good

**Comment by capedcrusader23** [comment]
you can add an image back.jpg found in views/image,
this feels more good @shakti97

**Comment by shakti97** [comment]
okay let me see @capedcrusader23

**Comment by prateekiiest** [comment]
LGTM

**Comment by shakti97** [comment]
screenshot 45
After Adding Background Img

**Comment by shakti97** [comment]
is there any problem in this PR? @jaskirat2000

**Pull request merged**
