### PR TITLE
:sparkles: improved quality and readability of code

### LINKED ISSUE #100: Improve the quality of the code
Quality of the code can be improved by -
1. linting the code
2. Optimise the mongoose query 
3. use of es6 
4. Added prettier to pretify the code .

### PR DESCRIPTION
**Pull request by Rupeshiya**
### **Problem**
_Trying to improve the quality and readability of the code._
### **Issue this PR referred to**
_`Fixes #100 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/100) for more details_

### **Solution of problem**
1.LInted the code using eslint to increase the readability of the code.
2.Optimised the mongoose query. 
3. Tried to implement es6 .
4. Defined lots of undefined variables.
5. Added prettier to pretify code along with eslint.

### **Before and After Screenshots**
_**Before** [How was it earlier, add it here]_

_**After** [How it looks now, add it here]_

### **Type of Change**
- [x] Bug fix
- [x] New Feature
- [ ] Development of UI/UX prototypes
- [x] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [ ] I have updated the Readme accordingly
- [x] I made PR within **development branch only**

### CODE REVIEW

**Comment by lakshyabatman** [comment]
Your branch has conflicts, make sure you solve it first :)

**Comment by iamgrawal** [comment]
Hey @Rupeshiya , there are still conflicts. Please resolve the conflicts first. 
And it would be great if you can change your description to the specified pull request template. You can see the template [here](https://raw.githubusercontent.com/codeuino/Social-Platform-Donut/master/PR_Template.md)

**Comment by Rupeshiya** [comment]
@iamgrawal , two days ago, I fixed the conflicts and now it's again arises because some of the PR has been merged . And again if any PR will get merged before merging  my updated PR then again conflicts will arise.
But going to fix the conflicts once again .

**Comment by iamgrawal** [comment]
@Rupeshiya Okay, once done let me know. Also, it would be great if you can add prettier as well.
You can refer to this link for integration, [https://prettier.io/docs/en/eslint.html](https://prettier.io/docs/en/eslint.html)

**Comment by Rupeshiya** [comment]
@iamgrawal  , Please check .

**Pull request merged**
