### PR TITLE
Issue #86

### PR DESCRIPTION
**Pull request by amanbora**
Screenshot 2020-01-26 at 10 20 11 AM

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@amanbora please rebase your branch, your PR is having a conflict.

**Comment by vaibhavdaren** [comment]
```
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch
```

**Comment by amanbora** [comment]
@Rupeshiya is there any other modification required?

**Comment by devesh-verma** [comment]
@amanbora the codebase has changed, please have look at our new codebase.

**Pull request closed without merging**
