### PR TITLE
Create PR_Template.md

### PR DESCRIPTION
**Pull request by jaskirat2000**

### CODE REVIEW

**Comment by iamgrawal** [comment]
This PR is regarding the issue #110, Please refer to this issue for further references

**Comment by jaskirat2000** [comment]
Thanks we can close this one too since we made another PR

**Comment by iamgrawal** [comment]
@jaskirat2000 there is an update needed in the template for the fixes to the which issue.

**Comment by jaskirat2000** [comment]
Please let me know or make a PR .

**Pull request merged**
