### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by tharun143**

### CODE REVIEW

**Comment by invincibleJai** [comment]
@tharun143 pls updates description and was there any associated issue?

**Comment by tharun143** [comment]
description of waht? About the landing pages??

**Comment by invincibleJai** [comment]
@tharun143 what this PR is intend to do

**Comment by iamgrawal** [comment]
Hey @tharun143 , to which issue does this PR corresponds to? Can you specify the issue here?

**Comment by tharun143** [comment]
the issue is about the update the README.md with the updated pictures of the website

**Comment by tharun143** [comment]
@invincibleJai What description should I add to README.md

**Pull request closed without merging**
