### PR TITLE
added error page for uncaught requests

### LINKED ISSUE #142: Add 404 page
### **Description of the problem**
_404 page is not rendering on uncaught request_

### **How to solve**
_Add 404 page and render on uncaught request_

### **Expected Outcome**
_On uncaught request 404 page will be rendered_

@jaskirat2000  should I add this ??

### PR DESCRIPTION
**Pull request by Rupeshiya**
### **Problem**
_404 was not rendering on uncaught requests_

### **Issue this PR referred to**
_`Fixes #142 `, Refer to this [link](https://github.com/codeuino/Social-Platform-Donut/issues/142)_

### **Solution of problem**
_Added error page and then rendered on uncaught requests_

### **Before and After Screenshots**
_**Before** Only message was coming like `can't get URL`_

_**After** error1_

### **Type of Change**
- [ ] Bug fix
- [X] New Feature
- [X] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [X] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [ ] I have updated the Readme accordingly
- [X] I made PR within **development branch only**

### CODE REVIEW

**Comment by debck** [comment]
Add a screenshot of the error page.

**Comment by Rupeshiya** [comment]
**Since URL is uncaught so rendered the error page** 
error1

**Done !!**

**Comment by nurdtechie98** [comment]
@Rupeshiya pull request template please 🙈

**Comment by Rupeshiya** [comment]
> @Rupeshiya pull request template please

Done @nurdtechie98 !!

**Pull request merged**
