### PR TITLE
fixed frontend responsiveness

### PR DESCRIPTION
**Pull request by shreyanshjn**
resolves issue #68

### CODE REVIEW

**Comment by invincibleJai** [comment]
@shreyanshjn looks better

screenshot 2019-03-02 at 12 11 27 am

**Comment by invincibleJai** [comment]
@devesh-verma labels need to be updated.

**Comment by lakshyabatman** [comment]
I see you have just added a media queries in the css file, though it will be great if you add a gif for the same show a small walkthrough of the donut. :)

**Comment by shreyanshjn** [comment]
@lakshyabatman I did not get what I need to add more..Can you please describe it little more?

**Comment by lakshyabatman** [comment]
I meant to say, did you made the whole landing page responsive totally or just the heading, Attach a gif to show the result :)

**Comment by shreyanshjn** [comment]
frontend

**Comment by lakshyabatman** [comment]
LGTM :+1: , good job @shreyanshjn

**Comment by jaskirat2000** [comment]
Great work

**Pull request merged**
