### PR TITLE
The backend Logic for profile picture is added

### LINKED ISSUE #169: No Profile Picture image url link in schema
### **Description of the problem**
A user should have a profile picture and which can be added by having link of it as string in the schema model
### **How to solve**
I will update the schema and add image link object in it.

### **Expected Outcome**
User can add his/her custom profile picture.

I am assigning this task to myself.

### PR DESCRIPTION
**Pull request by lakshyabatman**
### **Problem**
Updated schema and local strategy for uploading profile picture with proper validation
### **Issue this PR referred to**
Fixes #169  
### **Solution of problem**
Added field in user schema and in updated local.js, the frontend can send picture and the url of the picture will be stored in database.

### **Type of Change**
- Small refactor

### **Checklist**
- My code follow the same style as the codebase
- My Code changed required change in documentation
- I have updated the Readme accordingly
- I made PR within **development branch only**

### CODE REVIEW

**Comment by lakshyabatman** [comment]
The signup route doesn't exist #172 and whoever creates the Signup page and route make sure to keep the name of input for file as "myImage".

**Comment by lakshyabatman** [comment]
@capedcrusader23 @TG1999  have a look

**Comment by lakshyabatman** [comment]
Now frontend is also integrated with backend, and saves profile pictures, though I want someone to make a redirect page after signing up or something which alerts user that he/she is signed up. :)

simplescreenrecorder-2019-04-08_23 47 36

**Comment by lakshyabatman** [comment]
@jaskirat2000 have a look on it and sorry for so many commits the user.ejs had so many issues :)

**Comment by lakshyabatman** [comment]
@rupeshiya  have a look on it, signup is totally working and integrated!

**Comment by Rupeshiya** [comment]
Great !!

**Pull request merged**
