### PR TITLE
add posts feature

### PR DESCRIPTION
**Pull request by TG1999**
Signed-off-by: tushar goel <tushar.goel.dav@gmail.com>

### CODE REVIEW

**Comment by TG1999** [comment]
#207 solved

**Comment by vaibhavdaren** [comment]
something is missing :dancer:

**Comment by lakshyabatman** [comment]
@TG1999  can you add comments, for easier understanding, please :)

**Comment by TG1999** [comment]
@vaibhavdaren what ?

**Comment by TG1999** [comment]
@lakshyabatman okie

**Comment by vaibhavdaren** [comment]
@lakshyabatman  can you explain @TG1999  about how to remove the merge commit.
I think he has squashed the merge commit also.
Nice work @TG1999

**Pull request closed without merging**
