### PR TITLE
PWA installed , frontend validation and user location module is added.

### PR DESCRIPTION
**Pull request by lakshyabatman**
In the last Pull Request, the commits were not merged, soI squashed them this time. 

- PWA is installed in the project and now Donut is a Progressive Web Application. We can later do more work on it, but till now it caches the entire application on the browser for offline use.
- The frontend validation module is added, though it is a basic one it reduces the code lines in every file where Validation is required as well as bring modularity in the project as well.
- User Location module is added, It can be added in any life cycle component of any view, where we can fetch user position coordinates. It only uses geolocation and works on promises. So tweaking it won't be a big issue.
- Postcard module is added and can be used by injecting data through props. It is totally based on Vuetify + Vue bootstrap, so can be updated very easily.
- Offline and online messages are added, in the App.vue, which pops over when the internet goes off and on, bringing better User Experience.

@vaibhavdaren, I haven't refactored the code yet, I'll do in nex commits :) .

### CODE REVIEW

**Comment by vaibhavdaren** [comment]
2 commits?
merge in 1

**Comment by lakshyabatman** [comment]
@vaibhavdaren , Sir cause the commits are for different modules, I thought keeping them in different commits would be easy to understand. :)

**Comment by vaibhavdaren** [comment]
can you amend the messages?

**Comment by lakshyabatman** [comment]
@vaibhavdaren , I have some unstaged files. I'll merge all commits as soon as I complete the task :)

**Pull request closed without merging**
