### PR TITLE
Small bugs in other-landing.ejs solved

### PR DESCRIPTION
**Pull request by lakshyabatman**
## **Problem**
There were issues in ajax request as well some external js files were added

### **Solution of problem**
AJAX issues were solved and external cdn js links added in codebase

### **Type of Change**
- [x] Bug fix
- [x] New Feature
- [x] Development of UI/UX prototypes
- [ ] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [x] My code follow the same style as the codebase
- [x] My Code changed required change in documentation
- [x] I have updated the Readme accordingly
- [x] I made PR within **development bran

### CODE REVIEW

**Comment by lakshyabatman** [comment]
@jaskirat2000 , as I referred in #139 , I updated the page again

**Comment by lakshyabatman** [comment]
@capedcrusader23

**Comment by capedcrusader23** [comment]
i have made some changes  @lakshyabatman ,have a look at those changes.

**Comment by lakshyabatman** [comment]
@capedcrusader23 , updated the upDownVote again, please ask in the slack about removing the updownvote logic.
@jaskirat2000 someone changed the schema without letting us know, and removed the function for updownvote.

**Comment by nurdtechie98** [comment]
@lakshyabatman the changes were made in #113.

**Comment by lakshyabatman** [comment]
@nurdtechie98 , thanks for letting us know. :)

**Pull request merged**
