### PR TITLE
beautify and clean readme

### PR DESCRIPTION
**Pull request by nurdtechie98**
### **Problem**
Readme.md was fairly plaintext and needed a bit beautification to make it look attractive.
 
### **Solution of problem**
In an attempt to make the  readme  good looking I made the following changes:
* [x] add a logo
* [X] align few elements
* [X] added a few badges 

### **Before and After Screenshots**
**Before**
Imgur
Imgur
**After**
Imgur 
Imgur

### **Type of Change**
- [ ] Bug fix
- [ ] New Feature
- [ ] Development of UI/UX prototypes
- [X] Small refactor
- [ ] Change in Documentation

### **Checklist**
- [X] My code follow the same style as the codebase
- [ ] My Code changed required change in documentation
- [X] I have updated the Readme accordingly
- [X] I made PR within **development branch only**

With respect to #111 
Let me know if it is fine to have a logo. I took the initiative to make it look good. I'll be happy to close the PR in case it is a problem.

### CODE REVIEW

**Comment by nurdtechie98** [comment]
@jaskirat2000 @capedcrusader23 please review.

**Comment by jaskirat2000** [comment]
To me it looks good, just a small change needed in this that the screenshots which are placed can you make all those of same size ? And 3 screenshots in 1 line, moreover in frontend repo there are few pages which are not placed here, those all please add and then this PR would be good to merge, waiting for your commit.
Thanks

**Comment by nurdtechie98** [comment]
@jaskirat2000 fixed the image part. Let me know further changes

**Comment by jaskirat2000** [comment]
Thanks

**Pull request merged**
